seapath/meta-seapath

- recipes-kernel/linux/linux-mainline-rt.inc
Corrects the following error which occurs during kernel compilation
error: Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please
install libelf-dev, libelf-devel or elfutils-libelf-devel
Signed-off-by: Peter Smith <salerio@gmail.com>
> linux/linux-mainline-rt.inc: add elfutils-native to kernel DEPENDS

- recipes-votp/system-config/system-config/votp-loadkeys.service
Load US keys instead of FR in votp-loadkeys systemd service.
Signed-off-by: Eloi Bail <eloi.bail@savoirfairelinux.com>
> recipes-votp/system-conf: load US keys

- recipes-core/images/seapath-guest-common.inc
It will be recommended to containerize the workload as much as possible,
the guest image needs to be able to run docker containers since it will
be the "recommended" way of doing things.
> Guest image: Add docker

- conf/distro/seapath-common.inc
- recipes-extended/libvirt/files/libvirtd.service
- recipes-extended/libvirt_6.3/README
- recipes-extended/libvirt_6.3/libvirt-python.inc
- recipes-extended/libvirt_6.3/libvirt/0001-build-drop-unnecessary-libgnu.la-reference.patch
- recipes-extended/libvirt_6.3/libvirt/0001-ptest-Remove-Windows-1252-check-from-esxutilstest.patch
- recipes-extended/libvirt_6.3/libvirt/0001-to-fix-build-error.patch
- recipes-extended/libvirt_6.3/libvirt/configure.ac-search-for-rpc-rpc.h-in-the-sysroot.patch
- recipes-extended/libvirt_6.3/libvirt/dnsmasq.conf
- recipes-extended/libvirt_6.3/libvirt/gnutls-helper.py
- recipes-extended/libvirt_6.3/libvirt/hook_support.py
- recipes-extended/libvirt_6.3/libvirt/install-missing-file.patch
- recipes-extended/libvirt_6.3/libvirt/libvirt-1.0.3-fix-thread-safety-in-lxc-callback-handling.patch
- recipes-extended/libvirt_6.3/libvirt/libvirt-use-pkg-config-to-locate-libcap.patch
- recipes-extended/libvirt_6.3/libvirt/libvirtd.conf
- recipes-extended/libvirt_6.3/libvirt/libvirtd.sh
- recipes-extended/libvirt_6.3/libvirt/qemu-fix-crash-in-qemuOpen.patch
- recipes-extended/libvirt_6.3/libvirt/run-ptest
- recipes-extended/libvirt_6.3/libvirt/runptest.patch
- recipes-extended/libvirt_6.3/libvirt/tools-add-libvirt-net-rpc-to-virt-host-validate-when.patch
- recipes-extended/libvirt_6.3/libvirt_6.3.0.bb
Take libvirt recipe from meta-virtualization (hardknott branch) to bump
its version to 6.3.0.
Libvirt 6.3.0 is required to do solve bug causing issue #22 (virsh
migrate returning 1 instead of 0 even though there was no problem)
> libvirt: bump version to 6.3.0

- recipes-votp/system-config/system-config/efi/swupdate_hawkbit.sh
- recipes-votp/system-upgrade/files/switch_bootloader.sh
fixes 2 bugs with swupdate:
switch_bootloader.sh: fix for some UEFI behavior
Some UEFI firmware tend to remove from the boot order all slots that are
explicitely disabled (if they are disabled, they have nothing to do in
the boot order).
switch_bootloader.sh assume both Seapath slots are present in the boot
order, but since the UEFI may have removed the disabled slot, this may
not be the case.
This fix makes switch_bootloader.sh working even if both slots are not
in the boot order
system-config: fix typo in swupdate_hawkbit.sh
Fix typo in check_health.
> Swupdate bugs

- recipes-core/systemd/files/resolved.conf
- recipes-core/systemd/systemd_%.bbappend
By default systemd-resolved, the DNS client use by SEAPATH use Goolge DNS servers is there no DNS server configured by systemd-networkd to always have a DNS server configured.
In SEAPATH the DNS servers configuration is done during the setup step is if during this step no DNS server was provided we condidered it is besause it is wanted and we do not want to failback to Google DNS servers.
> recipes-core/systemd: remove default DNS server

- recipes-bsp/grub/files/votp-monitor/grub-efi.cfg
- recipes-bsp/grub/files/votp-no-iommu/grub-efi.cfg
- recipes-bsp/grub/files/votp-vm/grub-efi.cfg
- recipes-bsp/grub/files/votp/grub-efi.cfg
- wic/mkbiosdisk.wks.in
IPv6 in SEAPATH has not been taken into account and tested. For security
reasons it is better to disable it.
The IPv6 disabling is done in kernel parameters to avoid givin the
possibility de re-enabled at runtime.
The IPv6 can easily be restored if necessary by deleting the kernel
parameter.
> kernel parameters: disable IPv6

- recipes-cgl/cluster-glue/cluster-glue_%.bbappend
- recipes-core/images/seapath-host-common-ha.inc
- recipes-extended/msmtp/msmtp_%.bbappend
This commit adds and configure msmtp, to be able to send emails from
seapath
> pacemaker/glue: add smtp capability

- classes/security/pam-policy.bbclass
- conf/distro/seapath-common.inc
right now the unsafe-pam policy is available only if using the hardening
is enabled, whichmakes it impossible to build a dbg image (unsafe-pam
enabled) while using "no security" distro feature.
This patch makes it possible by enabling unsafe-pam for all seapath
images.
> unsafe pam-policy: make feature available for all seapath images

- recipes-extended/ceph/ceph_%.bbappend
A limit can now be set in seapath.conf build setting file, with the
SEAPATH_PARALLEL_MAKE variable.
> Remove ceph parallelization build limit by default

- classes/security/readonly.inc
- conf/machine/votp-host.conf
- conf/machine/votp-monitor.conf
Right now the init.sh script (used for overlay) is enabled only when the
readonly distro feature is enabled.
This changes allows the overlay to work whether readonly is enabled or
not.
> init.sh: move kernel boot argument to machines

- recipes-bsp/grub/files/grub-efi.cfg.in
efi=runtime is needed for efi vars to work in vm.
> grub-efi: remove extra ipv6.disable and add efi=runtime

- conf/machine/votp-no-iommu.conf
Right now the init.sh script (used for overlay) is enabled only when the
readonly distro feature is enabled.
This changes allows the overlay to work whether readonly is enabled or
not.
A precedent commit already made that changes for host and monitor vm,
this commit is for the no-iommu machine
> init.sh: move kernel boot argument to machine (no-iommu)

- recipes-extended/ceph/ceph_%.bbappend
> Ceph recipe: silly typo in parallelisation limiting code

- recipes-core/images/seapath-dbg-common.inc
- recipes-support/netperf/netperf_%.bbappend
Signed-off-by: watare <aurelien.watare@gmail.com>
Add netperf to measure the latency of the virtual network. More info are available [here](https://www.redhat.com/en/blog/hands-vhost-net-do-or-do-not-there-no-try)
update the license-flag from "non-commercial" to " " as netperf is now in MIT. The recipe is available [here](http://cgit.openembedded.org/meta-openembedded/tree/meta-networking/recipes-support/netperf/netperf_git.bb?h=master)
> seapath-dbg-common.inc : add netperf

- recipes-core/images/seapath-host-common-virtu.inc
- recipes-extended/dpdk/dpdk_20.%.bbappend
To have dpdk-devbind install dpdk-tools. Create a symlink into /usr/sbin as it was done in the DPDK's recipe in for previous DPDK versions.
> seapath-host-common-virtu: install dpdk-tools

- recipes-core/images/seapath-flash-pxe.bb
- recipes-votp/flash-script/files/flash.sh
Install efitools and efibootmgr in flash PXE image and to keep PXE entry before SEAPATH entries move SEAPATH entries at the end of the boot order.
> Support UEFI on flash PXE image

- recipes-votp/python3-setup-ovs/python3-setup-ovs.bb
RDEPENDS python3-pyyaml is missing, it only works with cluster's images
because the package is included by crmsh.
Signed-off-by: Thibault Sourdin <thibault.sourdin@savoirfairelinux.com>
> python3-setup-ovs: add python3-pyyaml RDEPENDS

- recipes-core/kbd/kbd_2.5.0.bb
When building mutilple SEAPATH images kbd build failed. Bump kbd to version 2.5.0 to solve this issue.
Use the recipes kbd_2.5.0.bb from the poky master branch:
commit id: cf7d8894545b83f55420fa33f7848e1bfc6754ff
Issue: #51
> recipes-core/kbd: bump to version 2.5.0

- recipes-support/syslog-ng/files/syslog-ng@.service
The syslog-ng service create a socket, so it needs the network to be online and not just created.
Signed-off-by: Erwann Roussy <erwann.roussy@savoirfairelinux.com>
> syslog-ng: fix service dependencies

- recipes-cgl/cluster-resource-agents/resource-agents_4.5.0.bbappend
To follow the change introduce in the vm_manager pull request !17: https://github.com/seapath/vm_manager/pull/17, create the seapath directory OCF to stored SEAPATH resource agents scripts.
Signed-off-by: Mathieu Dupré <mathieu.dupre@savoirfairelinux.com>
> recipes-cgl/cluster-resource-agents: create a SEAPATH OCF directory

- recipes-kernel/linux/linux-mainline-rt_5.15.bb
Signed-off-by: Mathieu Dupré <mathieu.dupre@savoirfairelinux.com>
> linux-mainline-rt: bump to 5.15.92-rt57

- conf/machine/votp-host.conf
Change the KVM halt_poll_ns module parameter set by Grub to 0. The previous value -1 is an incorrect value. To disable halt_poll_ns (this is what we want for real-time purpose) we have to set halt_poll_ns to 0.
Change-Id: I7d2f8718b6f1251a2259488c5e9a8d5fa4cdcffe
> machine/votp-host: fix KVM halt_poll_ns module parameter

- conf/distro/seapath-common.inc
Previously, 'PREFERRED_VERSION' was used to specify the preferred version of a recipe in the 'distro' module. With this if the version is not found a warning will be raised and another version is used instead. To avoid this, 'REQUIRED_VERSION' is now used instead of 'PREFERRED_VERSION'. This generates an error if the required version is not found, instead of a warning. This change should help to prevent unexpected behavior and make the code more robust.
> distro: replace PREFERRED_VERSION by REQUIRED_VERSION
